#!/usr/bin/bash
# Here the system will be configured

# Monitor Setup
# Monitor1 is the primary monitor

#monitor1="DP-1"
#monitor2="HDMI-1"

# Persistent refresh rates

#rr1="165.00"
#rr2="60.00"

# From left to right
# Up to 3 monitors in the array

#monitors=( "$monitor2" "$monitor1" )
#refresh=( "60.00" "165.00" )
